# Generated by Django 5.2.3 on 2025-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('service', models.CharField(choices=[('consultation', 'Consultation générale'), ('urgence', 'Urgence dentaire'), ('detartrage', 'Détartrage'), ('orthodontie', 'Orthodontie'), ('implant', 'Implantologie'), ('blanchiment', 'Blanchiment'), ('esthetique', 'Esthétique dentaire'), ('pediatrie', 'Dentisterie pédiatrique')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
