# Generated by Django 4.2.7 on 2025-07-15 04:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('lu', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format: +225XXXXXXXX', regex='^\\+?225?[0-9]{8,10}$')], verbose_name='Téléphone')),
                ('sujet', models.CharField(max_length=100, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dentiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dentistes/', verbose_name='Photo')),
                ('linkedin', models.URLField(blank=True, verbose_name='Profil LinkedIn')),
                ('actif', models.BooleanField(default=True, verbose_name='Dentiste actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dentiste',
                'verbose_name_plural': 'Dentistes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True)),
                ('ouverture_matin', models.TimeField(blank=True, null=True)),
                ('fermeture_matin', models.TimeField(blank=True, null=True)),
                ('ouverture_apres_midi', models.TimeField(blank=True, null=True)),
                ('fermeture_apres_midi', models.TimeField(blank=True, null=True)),
                ('ferme', models.BooleanField(default=False, verbose_name='Fermé ce jour')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['jour'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('description', models.TextField(verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('prix_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix minimum')),
                ('prix_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix maximum')),
                ('duree_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée en minutes')),
                ('actif', models.BooleanField(default=True, verbose_name='Service actif')),
                ('icone', models.CharField(default='ri-health-book-line', max_length=50, verbose_name='Icône Remix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image du service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format téléphone invalide. Exemple: +225 07 08 09 10', regex='^\\+225\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}\\s?\\d{2}$|^\\d{10}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_souhaitee', models.DateField(verbose_name='Date souhaitée')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message complémentaire')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_confirmee', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure confirmées')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service', verbose_name='Service demandé')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-created_at'],
            },
        ),
    ]
